### ISSUE TITLE
Animation doesn't fire on replay

### ISSUE THREAD

**Issue by anjapatel** [anjapatel/namegenerator#2]
But it works when the page loads!

**Comment by cr3ative** [comment]
Gotcha! I've submitted this in #4. 

- It didn't fire on replay as it was already shown. We hide it before showing it now, which makes the animation fire again.
- It worked on page-load for the same reason, and I've removed that for now, so that the user has to press Replay to play for the first time. You might not want that, but it made debugging easier.
